### ISSUE TITLE
SSC Editor falls over when + included in gambit input

### ISSUE THREAD

**Issue by hipitihop** [silentrob/superscript#111]
To reproduce:

1. add gambit input "+ list events" add response and save.
1. in real time interface (http://localhost:3000) enter any message.

terminal output follows:
```
/superscript-editor/node_modules/superscript/node_modules/lemmer/node_modules/node-wordnet/node_modules/es6-shim/es6-shim.js:1073
      return new OrigRegExp(pattern, flags);
             ^
SyntaxError: Invalid regular expression: /^+ list events$/: Nothing to repeat
    at RegExp (native)
    at new RegExp (/home/ubuntu/superscript-editor/node_modules/superscript/node_modules/lemmer/node_modules/node-wordnet/node_modules/es6-shim/es6-shim.js:1073:14)
    at /home/ubuntu/superscript-editor/node_modules/superscript/lib/topics/topic.js:143:39
    at Object.exports.postParse (/home/ubuntu/superscript-editor/node_modules/superscript/lib/parse/regexreply.js:273:3)
    at eachGambitHandle (/home/ubuntu/superscript-editor/node_modules/superscript/lib/topics/topic.js:112:18)
    at /home/ubuntu/superscript-editor/node_modules/superscript/node_modules/async/lib/async.js:118:13
    at Array.forEach (native)
    at _each (/home/ubuntu/superscript-editor/node_modules/superscript/node_modules/async/lib/async.js:39:24)
    at Object.async.each (/home/ubuntu/superscript-editor/node_modules/superscript/node_modules/async/lib/async.js:117:9)
    at done (/home/ubuntu/superscript-editor/node_modules/superscript/lib/topics/topic.js:98:19)
    at done (/home/ubuntu/superscript-editor/node_modules/superscript/node_modules/async/lib/async.js:128:19)
    at Promise.<anonymous> (/home/ubuntu/superscript-editor/node_modules/superscript/node_modules/async/lib/async.js:25:16)
    at Promise.<anonymous> (/home/ubuntu/superscript-editor/node_modules/mongoose/node_modules/mpromise/lib/promise.js:177:8)
    at emitOne (events.js:77:13)
    at Promise.emit (events.js:169:7)
    at Promise.emit (/home/ubuntu/superscript-editor/node_modules/mongoose/node_modules/mpromise/lib/promise.js:84:38)

npm ERR! Linux 3.13.0-48-generic
npm ERR! argv "/home/ubuntu/.nvm/versions/io.js/v2.3.0/bin/iojs" "/home/ubuntu/.nvm/versions/io.js/v2.3.0/bin/npm" "start"
npm ERR! node v2.3.0
npm ERR! npm  v2.11.1
npm ERR! code ELIFECYCLE
npm ERR! superscript-editor@0.1.7 start: `node app`
npm ERR! Exit status 1
```

**Comment by silentrob** [comment]
Verified.

**Comment by hipitihop** [comment]
Apologies, this may be SSC Editor specific and I only just found it has its own repo.

**Comment by silentrob** [comment]
I will add a test in github.com/silentrob/superscript to verify. The problem is caused by not escaping unsafe regular expression characters during the pre-save hook whan saving the gambit.

The function do to that is here (https://github.com/silentrob/superscript/blob/master/lib/utils.js#L90-L96) but I'm just trying to figure out when/where is the right time to call that.

**Comment by silentrob** [comment]
This should fix it.

**Comment by hipitihop** [comment]
From report to fixed, in 60 min, impressive. Many thanks. Careful you might set a precedent in expected response time here :-)
