### ISSUE TITLE
Installing SupersctriptJS locally

### ISSUE THREAD

**Issue by matteoraggi** [silentrob/superscript#147]
I have installed nodejs and mongodb on windows 10, then I am gone to the propmpt of nodejs and I executed this line: `npm install --global superscript` then the prompt after about a minute write that it don't look to be all right (I should install Python? from npm or .exe?):

```
Your environment has been set up for using Node.js 4.0.0 (x64) and npm.

C:\Users\Anonymous>npm install --global superscript
npm WARN engine stream-worker@0.0.1: wanted: {"node":"~0.10.0"} (current: {"node":"4.0.0","npm":"2.14.2"})
npm WARN engine levelgraph@0.10.4: wanted: {"node":">= 0.10 < 0.13","npm":">= 1.4.0","iojs":">= 1.0.0"} (current: {"node":"4.0.0","npm":"2.14.2"})
/

> kerberos@0.0.7 install C:\Users\Anonymous\AppData\Roaming\npm\node_modules\superscript\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos
> (node-gyp rebuild 2> builderror.log) || (exit 0)

\
C:\Users\Anonymous\AppData\Roaming\npm\node_modules\superscript\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
-

> re2@1.3.1 install C:\Users\Anonymous\AppData\Roaming\npm\node_modules\superscript\node_modules\node-normalizer\node_modules\re2
> node-gyp rebuild

\
C:\Users\Anonymous\AppData\Roaming\npm\node_modules\superscript\node_modules\node-normalizer\node_modules\re2>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
gyp ERR! configure error
ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:116:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:71:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Anonymous\AppData\Roaming\npm\node_modules\superscript\node_modules\node-normalizer\node_modules\re2
gyp ERR! node -v v4.0.0
gyp ERR! node-gyp -v v3.0.1
gyp ERR! not ok
\

> bson@0.2.22 install C:\Users\Anonymous\AppData\Roaming\npm\node_modules\superscript\node_modules\mongoose\node_modules\mongodb\node_modules\bson
> (node-gyp rebuild 2> builderror.log) || (exit 0)

C:\Users\Anonymous\AppData\Roaming\npm\node_modules\superscript\node_modules\mongoose\node_modules\mongodb\node_modules\bson>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
-

> leveldown@0.10.5 install C:\Users\Anonymous\AppData\Roaming\npm\node_modules\superscript\node_modules\sfacts\node_modules\leveldown
> node-gyp rebuild

\
C:\Users\Anonymous\AppData\Roaming\npm\node_modules\superscript\node_modules\sfacts\node_modules\leveldown>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:116:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:71:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Anonymous\AppData\Roaming\npm\node_modules\superscript\node_modules\sfacts\node_modules\leveldown
gyp ERR! node -v v4.0.0
 node-gyp -v v3.0.1
gyp ERR! not ok
-
> WNdb@3.1.1 postinstall C:\Users\Anonymous\AppData\Roaming\npm\node_modules\superscript\node_modules\WNdb
> node unpack.js WNdb-3.1.tar.gz

Extracting WNdb-3.1.tar.gz

> wndb-with-exceptions@3.0.1 postinstall C:\Users\Anonymous\AppData\Roaming\npm\node_modules\superscript\node_modules\lemmer\node_modules\wndb-with-exceptions
> node unpack.js WNdb-3.0.tar.gz

npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--global" "superscript"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE

npm ERR! re2@1.3.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the re2@1.3.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the re2 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls re2
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Anonymous\npm-debug.log

C:\Users\Anonymous>
```

**Comment by mariusursache** [comment]
@matteoraggi did you manage to solve this?

**Comment by matteoraggi** [comment]
no, a friend installed it locally and shared it online to me trough a nat, for now I am doing tests in this way.

**Comment by slidenerd** [comment]
seems like it doesnt work on windows, i ran this on the mac but not on windows
