### ISSUE TITLE
input question

### ISSUE THREAD

**Issue by wac81** [silentrob/superscript#165]
return new OrigRegExp(pattern, flags);
             ^
SyntaxError: Invalid regular expression: /^(\s?(?:[\w-]*\s?){0,10})(?:\s*](\s?(?:[\w-]*\s?){0,20})[\s*|\s*)(\s?(?:[\w-]*\s?){0,20})$/: Unmatched ')'
    at RegExp (<anonymous>)
    at new RegExp (/home/nku/my_bot_final/node_modules/superscript/node_modules/lemmer/node_modules/node-wordnet/node_modules/es6-shim/es6-shim.js:1073:14)
    at complexFunction (/home/nku/my_bot_final/node_modules/superscript/lib/topics/common.js:124:19)
    at Object.exports.postParse (/home/nku/my_bot_final/node_modules/superscript/node_modules/ss-parser/lib/regexreply.js:311:3)
    at _doesMatch (/home/nku/my_bot_final/node_modules/superscript/lib/topics/common.js:123:14)
    at /home/nku/my_bot_final/node_modules/superscript/lib/topics/common.js:192:5
    at /home/nku/my_bot_final/node_modules/superscript/node_modules/async/lib/async.js:235:13
    at /home/nku/my_bot_final/node_modules/superscript/node_modules/async/lib/async.js:118:13
    at Array.forEach (native)
    at _each (/home/nku/my_bot_final/node_modules/superscript/node_modules/async/lib/async.js:39:24)
    at async.each (/home/nku/my_bot_final/node_modules/superscript/node_modules/async/lib/async.js:117:9)
    at _asyncMap (/home/nku/my_bot_final/node_modules/superscript/node_modules/async/lib/async.js:234:9)
    at Object.map (/home/nku/my_bot_final/node_modules/superscript/node_modules/async/lib/async.js:212:23)
    at populateGambitsComplete (/home/nku/my_bot_final/node_modules/superscript/lib/topics/common.js:81:13)
    at done (/home/nku/my_bot_final/node_modules/superscript/node_modules/async/lib/async.js:128:19)
    at Promise.<anonymous> (/home/nku/my_bot_final/node_modules/superscript/node_modules/async/lib/async.js:25:16)

**Comment by silentrob** [comment]
Wow, I have not hit this one before, do you know what the input match was?

**Comment by wac81** [comment]
maybe I have find the reason, there is some mistake in my superscriptDB
