### ISSUE TITLE
Bot crash error: Callback was already called.

### ISSUE THREAD

**Issue by Lewwwk** [silentrob/superscript#169]
On first interaction, bot is consistently crashing with the error: Callback was already called.

From the debug log:

```
  mquery find +0ms { _id: { '$in': [ 5633a718bfe8d65727cf0847 ] } } { fields: undefined }
  Common Try to match (clean)'~emohello' against ~emohello(?:\s*(\s?(?:[\w-]*\s?){0,2})\s*|\s*) (~emohello(?:\s*(\s?(?:[\w-]*\s?){0,2})\s*|\s*)) +102ms
  Common Try to match (lemma)'~emohello' against ~emohello(?:\s*(\s?(?:[\w-]*\s?){0,2})\s*|\s*) (~emohello(?:\s*(\s?(?:[\w-]*\s?){0,2})\s*|\s*)) +0ms
  Common Try to match (clean)'~emohello' against hell world (hell world) +1ms
  Common Try to match (lemma)'~emohello' against hell world (hell world) +0ms
  Common Try to match (clean)'~emohello' against request (request) +0ms
  Common Try to match (lemma)'~emohello' against request (request) +0ms
  Common Try to match (clean)'~emohello' against null (null) +1ms
  Common Try to match (lemma)'~emohello' against null (null) +0ms
  Common Try to match (clean)'~emohello' against null (null) +0ms
  Common Try to match (lemma)'~emohello' against null (null) +0ms
/Users/MichaelLewkowitz/Development/tipjuice/node_modules/superscript/node_modules/async/lib/async.js:23
            if (called) throw new Error("Callback was already called.");
                              ^
Error: Callback was already called.
    at /Users/MichaelLewkowitz/Development/tipjuice/node_modules/superscript/node_modules/async/lib/async.js:23:31
    at /Users/MichaelLewkowitz/Development/tipjuice/node_modules/superscript/node_modules/async/lib/async.js:237:17
    at /Users/MichaelLewkowitz/Development/tipjuice/node_modules/superscript/lib/topics/common.js:273:9
    at complexFunction (/Users/MichaelLewkowitz/Development/tipjuice/node_modules/superscript/lib/topics/common.js:171:5)
    at Object.exports.postParse (/Users/MichaelLewkowitz/Development/tipjuice/node_modules/superscript/node_modules/ss-parser/lib/regexreply.js:311:3)
    at _doesMatch (/Users/MichaelLewkowitz/Development/tipjuice/node_modules/superscript/lib/topics/common.js:123:14)
    at /Users/MichaelLewkowitz/Development/tipjuice/node_modules/superscript/lib/topics/common.js:192:5
    at /Users/MichaelLewkowitz/Development/tipjuice/node_modules/superscript/node_modules/async/lib/async.js:235:13
    at /Users/MichaelLewkowitz/Development/tipjuice/node_modules/superscript/node_modules/async/lib/async.js:118:13
    at Array.forEach (native)
    at _each (/Users/MichaelLewkowitz/Development/tipjuice/node_modules/superscript/node_modules/async/lib/async.js:39:24)
    at async.each (/Users/MichaelLewkowitz/Development/tipjuice/node_modules/superscript/node_modules/async/lib/async.js:117:9)
    at _asyncMap (/Users/MichaelLewkowitz/Development/tipjuice/node_modules/superscript/node_modules/async/lib/async.js:234:9)
    at Object.map (/Users/MichaelLewkowitz/Development/tipjuice/node_modules/superscript/node_modules/async/lib/async.js:212:23)
    at populateGambitsComplete (/Users/MichaelLewkowitz/Development/tipjuice/node_modules/superscript/lib/topics/common.js:81:13)
    at done (/Users/MichaelLewkowitz/Development/tipjuice/node_modules/superscript/node_modules/async/lib/async.js:128:19)
```

Any suggestions?

**Comment by silentrob** [comment]
That is the first time I have seen this error. Are you able to isolate it or reduce it down to something reproducable.

**Comment by Lewwwk** [comment]
I've tried:
- using the most basic script with one trigger and reply
- removing all versions of superscript and reinstalling

I'm on node 0.12.7 and mongo 3.0.2

Yesterday, if my memory isn't failing, did have the bot running with the basic telnet library install, but after doing some work on a new_user script have not been able to get the bot working, even after steps above.

**Comment by silentrob** [comment]
Okay, I will re-run the "hello world" on telnet and make sure everything is working as it should be.

**Comment by Lewwwk** [comment]
Update: I can't repo on a different system. Continuing to investigate.

**Comment by Lewwwk** [comment]
This was related to a mongo issue. Forced shutdown of all mongo processes and dropped the db. Will reopen if I can recreate in the future.
