### ISSUE TITLE
SS crasched adding the first gambit

### ISSUE THREAD

**Issue by matteoraggi** [silentrob/superscript#181]
hosted on koding.io I added my first gambit "is question":__startchat__
The the BOT stopped to answer me after receiving this error:

/home/MYUSERNAME/superscript-editor/node_modules/superscript/lib/topics/common.js:171
    callback(null, match);
                   ^
ReferenceError: match is not defined
    at complexFunction (/home/MYUSERNAME/superscript-editor/node_modules/superscript/lib/topics/common.js:171:20)
    at Object.exports.postParse (/home/MYUSERNAME/superscript-editor/node_modules/superscript/node_modules/ss-parser/lib/regexreply.js:311:3)
    at _doesMatch (/home/MYUSERNAME/superscript-editor/node_modules/superscript/lib/topics/common.js:123:14)
    at /home/MYUSERNAME/superscript-editor/node_modules/superscript/lib/topics/common.js:192:5
    at /home/MYUSERNAME/superscript-editor/node_modules/superscript/node_modules/async/lib/async.js:235:13
    at /home/MYUSERNAME/superscript-editor/node_modules/superscript/node_modules/async/lib/async.js:118:13
    at Array.forEach (native)
    at _each (/home/MYUSERNAME/superscript-editor/node_modules/superscript/node_modules/async/lib/async.js:39:24)
    at async.each (/home/MYUSERNAME/superscript-editor/node_modules/superscript/node_modules/async/lib/async.js:117:9)
    at _asyncMap (/home/MYUSERNAME/superscript-editor/node_modules/superscript/node_modules/async/lib/async.js:234:9)
    at Object.map (/home/MYUSERNAME/superscript-editor/node_modules/superscript/node_modules/async/lib/async.js:212:23)
    at populateGambitsComplete (/home/MYUSERNAME/superscript-editor/node_modules/superscript/lib/topics/common.js:81:13)
    at done (/home/MYUSERNAME/superscript-editor/node_modules/superscript/node_modules/async/lib/async.js:128:19)
    at Promise.<anonymous> (/home/MYUSERNAME/superscript-editor/node_modules/superscript/node_modules/async/lib/async.js:25:16)
    at Promise.<anonymous> (/home/MYUSERNAME/superscript-editor/node_modules/mongoose/node_modules/mpromise/lib/promise.js:177:8)
    at Promise.EventEmitter.emit (events.js:95:17)
    at Promise.emit (/home/MYUSERNAME/superscript-editor/node_modules/mongoose/node_modules/mpromise/lib/promise.js:84:38)
    at Promise.fulfill (/home/MYUSERNAME/superscript-editor/node_modules/mongoose/node_modules/mpromise/lib/promise.js:97:20)
    at Promise.resolve (/home/MYUSERNAME/superscript-editor/node_modules/mongoose/lib/promise.js:114:23)
    at /home/MYUSERNAME/superscript-editor/node_modules/mongoose/lib/model.js:2051:23
    at process._tickCallback (node.js:415:13)

**Comment by matteoraggi** [comment]
I have patched the problem moving some files that the setup was not doing by itself.
