### ISSUE TITLE
Error reinstalling ss on koding:

### ISSUE THREAD

**Issue by matteoraggi** [silentrob/superscript#182]
I was using SS, mongodb and nodejs at the lastest version:

/home/MYUSERNAME/superscript-editor/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:299
          throw err;
                ^
Error: Cannot find module 'superscript/lib/wordnet'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/MYUSERNAME/superscript-editor/plugins/cnet.js:5:10)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at requireDir (/home/MYUSERNAME/superscript-editor/node_modules/superscript/node_modules/require-dir/index.js:112:33)
    at SuperScript.loadPlugins (/home/MYUSERNAME/superscript-editor/node_modules/superscript/index.js:252:17)
    at new SuperScript (/home/MYUSERNAME/superscript-editor/node_modules/superscript/index.js:38:8)
    at NativeConnection.module.exports (/home/MYUSERNAME/superscript-editor/app.js:45:10)
    at NativeConnection.g (events.js:180:16)
    at NativeConnection.EventEmitter.emit (events.js:92:17)
    at open (/home/MYUSERNAME/superscript-editor/node_modules/mongoose/lib/connection.js:453:10)
    at NativeConnection.Connection.onOpen (/home/MYUSERNAME/superscript-editor/node_modules/mongoose/lib/connection.js:462:5)
    at /home/MYUSERNAME/superscript-editor/node_modules/mongoose/lib/connection.js:421:10
    at /home/MYUSERNAME/superscript-editor/node_modules/mongoose/lib/drivers/node-mongodb-native/connection.js:59:5
    at /home/MYUSERNAME/superscript-editor/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:296:11
 
npm ERR! superscript-editor@0.1.7 start: `node app`

**Comment by matteoraggi** [comment]
I have patched the problem moving some files that the setup was not doing by itself.
