### ISSUE TITLE
Crash on single word input (when chunking == false)

### ISSUE THREAD

**Issue by Lewwwk** [silentrob/superscript#215]
When a user provides a single word input such as `very` or `then`, superscript crashes. It looks to be that these words are removed through normalization, producing an undefined input which can't be resolved.

This only happens when chunking == false. 

Could also be related to #214 

```
  Script Message Recieved from '2' +2s very
  mquery findOne +2s { id: '2' } { fields: undefined }
Not Chunking
  Message Creating message from: +2s 
  Message Callback Early, empty msg +0ms
  User getTopic +2s answers
/Users/MichaelLewkowitz/Development/tipjuice/node_modules/superscript/lib/topics/topic.js:176
    tfidf.tfidfs(msg.lemString.tokenizeAndStem(), function (index, m, k) {
                              ^
TypeError: Cannot read property 'tokenizeAndStem' of undefined
    at _score (/Users/MichaelLewkowitz/Development/tipjuice/node_modules/superscript/lib/topics/topic.js:176:31)
    at Function.topicSchema.statics.findPendingTopicsForUser (/Users/MichaelLewkowitz/Development/tipjuice/node_modules/superscript/lib/topics/topic.js:210:24)
    at getreply (/Users/MichaelLewkowitz/Development/tipjuice/node_modules/superscript/lib/getreply.js:362:21)
    at messageItor (/Users/MichaelLewkowitz/Development/tipjuice/node_modules/superscript/index.js:84:5)
    at /Users/MichaelLewkowitz/Development/tipjuice/node_modules/superscript/node_modules/async/lib/async.js:235:13
    at iterate (/Users/MichaelLewkowitz/Development/tipjuice/node_modules/superscript/node_modules/async/lib/async.js:142:13)
    at async.eachSeries (/Users/MichaelLewkowitz/Development/tipjuice/node_modules/superscript/node_modules/async/lib/async.js:158:9)
    at _asyncMap (/Users/MichaelLewkowitz/Development/tipjuice/node_modules/superscript/node_modules/async/lib/async.js:234:9)
    at Object.mapSeries (/Users/MichaelLewkowitz/Development/tipjuice/node_modules/superscript/node_modules/async/lib/async.js:224:23)
    at /Users/MichaelLewkowitz/Development/tipjuice/node_modules/superscript/index.js:224:13
    at /Users/MichaelLewkowitz/Development/tipjuice/node_modules/superscript/index.js:157:12
    at /Users/MichaelLewkowitz/Development/tipjuice/node_modules/superscript/node_modules/async/lib/async.js:240:13
    at /Users/MichaelLewkowitz/Development/tipjuice/node_modules/superscript/node_modules/async/lib/async.js:150:25
    at /Users/MichaelLewkowitz/Development/tipjuice/node_modules/superscript/node_modules/async/lib/async.js:237:17
    at /Users/MichaelLewkowitz/Development/tipjuice/node_modules/superscript/index.js:152:7
    at new Message (/Users/MichaelLewkowitz/Development/tipjuice/node_modules/superscript/lib/message.js:48:12)
```

**Comment by silentrob** [comment]
This was not related to gh-214, but it is fixed now.
