### ISSUE TITLE
getting started / WNdb has been superceded

### ISSUE THREAD

**Issue by dcsan** [silentrob/superscript#248]
I'm guessing the [installing](https://github.com/silentrob/superscript/wiki/Installing) page is intentionally left blank because you're not ready for lots of traffic, but the startup is giving me some glitches right now... It's been awhile but I thought the initial setup involved:

```
bin/bot-init.js
bin/parse.js
```

but getting the errors below

```
$ bin/parse.js 
parse topics
Please 'npm install WNdb' before using WordNet module or specify a dict directory.


➜  superscript git:(master) ✗ npm install WNdb
npm WARN deprecated WNdb@3.1.2: WNdb has been superceded by wordnet-db.  Please update your dependency.
npm WARN superscript@0.11.20 No license field.


➜  superscript git:(master) ✗ bin/parse.js 
parse topics
Please 'npm install WNdb' before using WordNet module or specify a dict directory.
/Users/dc/dev/rnd/superscript/node_modules/natural/lib/natural/wordnet/wordnet.js:143
      throw e;
      ^

Error: ENOENT: no such file or directory, scandir '/Users/dc/dev/rnd/superscript/node_modules/WNdb/dict'
    at Error (native)
    at Object.fs.readdirSync (fs.js:856:18)
    at Object.<anonymous> (/Users/dc/dev/rnd/superscript/node_modules/WNdb/index.js:4:31)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at new WordNet (/Users/dc/dev/rnd/superscript/node_modules/natural/lib/natural/wordnet/wordnet.js:140:18)

$ npm install wordnet-db

> wordnet-db@3.1.2 postinstall /Users/dc/dev/rnd/superscript/node_modules/wordnet-db
> node unpack.js WNdb-3.1.tar.gz

Extracting WNdb-3.1.tar.gz

superscript@0.11.20 /Users/dc/dev/rnd/superscript
└── wordnet-db@3.1.2  extraneous

npm WARN superscript@0.11.20 No license field.

$ bin/parse.js       
parse topics
Please 'npm install WNdb' before using WordNet module or specify a dict directory.
/Users/dc/dev/rnd/superscript/node_modules/natural/lib/natural/wordnet/wordnet.js:143
      throw e;

```

**Comment by dcsan** [comment]
tried changing to 

```json
  "dependencies": {
    "wordnet-db": "~3.1.1",
```

and did a clean install.

always the install fails the first time with:

```
npm WARN superscript@0.11.20 No license field.
npm ERR! Darwin 15.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE

npm ERR! WNdb@3.1.1 postinstall: `node unpack.js WNdb-3.1.tar.gz`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the WNdb@3.1.1 postinstall script 'node unpack.js WNdb-3.1.tar.gz'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the WNdb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node unpack.js WNdb-3.1.tar.gz
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs WNdb
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls WNdb
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/dc/dev/rnd/superscript/npm-debug.log
```

but then I just run it a second time and it will run. 
however i guess something internally still depends on WNdb

```
$ npm install
npm WARN deprecated WNdb@3.1.1: WNdb has been superceded by wordnet-db.  Please update your dependency.

> WNdb@3.1.1 postinstall /Users/dc/dev/rnd/superscript/node_modules/WNdb
> node unpack.js WNdb-3.1.tar.gz

Extracting WNdb-3.1.tar.gz

superscript@0.11.20 /Users/dc/dev/rnd/superscript
├─┬ conceptnet@0.0.1 (git://github.com/silentrob/conceptnet.git#bce5124e767ab3ea852c12016508b6f56bbb3cad)
│ └─┬ knex@0.5.16

```

so it kind of installs but then

```
$ node index.js 
Please 'npm install wndb-with-exceptions' before using WordNet module or specify a dict directory.
/Users/dc/dev/rnd/superscript/node_modules/node-wordnet/lib/wordnet.js:40
        throw e;
              ^
```
ok...
```
$ npm install wndb-with-exceptions

> wndb-with-exceptions@3.0.1 postinstall /Users/dc/dev/rnd/superscript/node_modules/wndb-with-exceptions
> node unpack.js WNdb-3.0.tar.gz

superscript@0.11.20 /Users/dc/dev/rnd/superscript
└── wndb-with-exceptions@3.0.1 

npm WARN superscript@0.11.20 No license field.
```

hmm, maybe getting somewhere

```
$ bin/bot-init.js bot3
Creating bot3 bot with a telnet client.
   create : /Users/dc/dev/rnd/superscript/bot3/package.json
   create : /Users/dc/dev/rnd/superscript/bot3/topics/main.ss

```

```
➜  superscript git:(master) ✗ bin/parse.js bot3
parse topics
fs.js:797
  return binding.stat(pathModule._makeLong(path));
                 ^
Error: ENOENT, no such file or directory './topics'
    at Error (native)
    at Object.fs.statSync (fs.js:797:18)
    at Object.walk (/Users/dc/dev/rnd/superscript/node_modules/ss-parser/lib/utils.js:136:10)
    at Object.loadDirectory (/Users/dc/dev/rnd/superscript/node_modules/ss-parser/lib/index.js:55:11)
    at /Users/dc/dev/rnd/superscript/bin/parse.js:23:11
    at FSReqWrap.cb [as oncomplete] (fs.js:226:19)

```
maybe i'm not meant to do that.

so anyway, cd to the new bot directory, install and run.

```
$ cd bot3
$ npm install
$ DEBUG=* node server.js 
  Normalizer Loaded File +0ms { key: '_sys', file: 'systemessentials.txt' }
  Normalizer Loaded File +6ms { key: '_extra', file: 'substitutes.txt' }
  Normalizer Loaded File +132ms { key: '_contractions', file: 'contractions.txt' }
  Normalizer Loaded File +13ms { key: '_interjections', file: 'interjections.txt' }
  Normalizer Loaded File +55ms { key: '_britsh', file: 'british.txt' }
  Normalizer Loaded File +174ms { key: '_spellfix', file: 'spellfix.txt' }
  Normalizer Loaded File +309ms { key: '_texting', file: 'texting.txt' }
  Normalizer Done Reading Subs +10ms
  Normalizer Done Loading files +0ms
  SS:Gambit Normaizer Loaded. +0ms
  mquery count +0ms {} {}
  mquery count +1ms {} {}
undefined:1
undefined
^
SyntaxError: Unexpected token u
    at Object.parse (native)
    at /Users/dc/dev/rnd/superscript/bot3/node_modules/superscript/lib/topics/import.js:224:30
    at fs.js:263:20
    at FSReqWrap.oncomplete (fs.js:95:15)
```

so, not sure if there was an extra step here to get setup.

I found [this thread from january last year](https://github.com/silentrob/superscript/issues/38) hah, so I did eventually get things running then. But not sure where to go from here.

**Comment by dcsan** [comment]
OK i found this page, which makes it clearer how to get going.
http://superscriptjs.com/starter/quickstart

**Comment by SephVelut** [comment]
This issue still exists

**Comment by Samurais** [comment]
It is addressed in README.
https://github.com/superscriptjs/superscript

![image](https://cloud.githubusercontent.com/assets/3538629/19415996/4c5f3cc2-93b6-11e6-91e6-d39743a11c78.png)
