### ISSUE TITLE
problems with getting started / Cannot read property 'random' of undefined

### ISSUE THREAD

**Issue by dcsan** [silentrob/superscript#38]
I followed the tutorial and have an out of the box bot but trying `hello` causes it to crash

```bash
cbot> node server.js
TCP server running on port 2000.



User '127.0.0.1:55384' has connected.


/Users/dc/node_modules/superscript/lib/getreply.js:359
    if (gIncludes[topic] || gLineage[topic]) {
                 ^
TypeError: Cannot read property 'random' of undefined
    at getreply (/Users/dc/node_modules/superscript/lib/getreply.js:359:18)
    at internalizeHandle (/Users/dc/node_modules/superscript/index.js:125:9)
    at messageItor (/Users/dc/node_modules/superscript/index.js:135:5)
    at /Users/dc/node_modules/superscript/node_modules/async/lib/async.js:235:13
    at iterate (/Users/dc/node_modules/superscript/node_modules/async/lib/async.js:142:13)
    at async.eachSeries (/Users/dc/node_modules/superscript/node_modules/async/lib/async.js:158:9)
    at _asyncMap (/Users/dc/node_modules/superscript/node_modules/async/lib/async.js:234:9)
    at Object.mapSeries (/Users/dc/node_modules/superscript/node_modules/async/lib/async.js:224:23)
    at /Users/dc/node_modules/superscript/index.js:190:11
    at /Users/dc/node_modules/superscript/index.js:155:12
```

client
```
ref> telnet localhost 2000
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
Welcome to the Telnet server!
Hello 127.0.0.1:55384! Type /quit to disconnect.

You> hello
Connection closed by foreign host.
```

bot script is currently:

```bash
superscript> cd cbot 
cbot> parse
parse topics
File data.json already exists, remove file first or use -f to force save.

cbot> parse -f
parse topics
Time to Process 1.167 seconds
Number of topics 1 parsed.
Number of triggers 1 parsed.
Number of replies 6 parsed.
Saved output to data.json

cbot> cat data.json 
{"gTopicFlags":{"random":[]},"gTopics":{"random":{"7Xw2HqOY":{"trigger":"~emohello(?:\\s*(\\s?(?:[\\w]*\\s?){0,2})\\s*|\\s*)","options":{"isQuestion":false,"qType":false,"qSubType":false,"filter":false},"reply":{"Cp8L6Y7M":"Hi!","VXqL8u2v":"Hi, how are you?","hZYpXFAI":"How are you?","eo5vDdGE":"Hello","p9OBmtyB":"Howdy","eZ67xZjX":"Ola"}}}},"gPrevTopics":{},"gSorted":{"topics":{"random":["7Xw2HqOY"]},"thats":{},"that_trig":{}},"keywords":"{\"documents\":[],\"_idfCache\":{}}","checksums":{"./topics/main.ss":"a307a35116dcfadd055582b4f73c4041c2811a71"}}%                                                    

cbot> cat topics/main.ss 
+ ~emohello [*~2]
- Hi!
- Hi, how are you?
- How are you?
- Hello
- Howdy
- Ola%   

```

**Comment by dcsan** [comment]
FWIW i tried removing anything that has "random" options.

```
+ hello bot
- hello, human!

+ gday
- good day to you
```

this still crashes with the same error msg

```
TypeError: Cannot read property 'random' of undefined
    at getreply (/Users/dc/node_modules/superscript/lib/getreply.js:359:18)

```

**Comment by dcsan** [comment]
so its failing possibly cos there is no random topic, so i added one:

```
> topic random
  + sup
  - sup dude
< topic
```

but that still fails.

**Comment by dcsan** [comment]
digging into what the error is, the line from the err code is:
so i guess `gIncludes: undefined`

```
checking topic: random
gIncludes: undefined

/Users/dc/node_modules/superscript/lib/getreply.js:363
    if (gIncludes[topic] || gLineage[topic]) {
                 ^
TypeError: Cannot read property 'random' of undefined

```

**Comment by dcsan** [comment]
this is set here

    gIncludes = options.system.includes;

whereas at startup:

```js
options.system { topicFlags: { random: [] },
  sorted: { topics: { random: [Object] }, thats: {}, that_trig: {} },
  topics: { random: { xnejtYYj: [Object], ztSzP4XJ: [Object], FTr1QRYk: [Object] } },
  thats: {},
  includes: undefined,
  lineage: undefined,
  plugins: 
   [ oppisite: [Function],
     rhymes: [Function],
     syllable: [Function],
     letterLookup: [Function],
     wordLength: [Function],
     nextNumber: [Function],
     createFact: [Function],
```

so somethings are not being set

**Comment by silentrob** [comment]
Thanks for the feedback.

gIncludes was removed in 0.3.x and my getReply does not have a line 363. Let me start their and see whats going on.

**Comment by silentrob** [comment]
I think you might have a local copy of superscript in your node modules folder and a global one.. The global is using the new parse function so I know that is current, but your local one needs to be deleted and updated. Check your package.json

**Comment by dcsan** [comment]
ok i was wondering about that and if i really needed the global one - makes debugging a bit harder and confusing.

**Comment by silentrob** [comment]
Ya, I did that because I wanted some sort of init app that generated a bot project, and make the onboarding easier.. but perhaps that should be its own project. 

Let me know if your unblocked and feel free to close this issue.

**Comment by dcsan** [comment]
sorry to be dense, but what is the recommended way to configure an app.
can i run this without the global install? its failing as i have this setup:

```
superscript> node cbot/server.js 

module.js:340
    throw err;
          ^
Error: Cannot find module 'superscript'
```

I currently have my bot in a `cbot` directory, inside the checked out superscript repo
should i separate these or somehow put the app a level up, or some other layout?

I notice server.js starts with:

```js
var net             = require("net");
var superscript     = require("superscript");
```

layout
```
app/

├── cbot
│   ├── data.json
│   ├── package.json
│   ├── plugins
│   ├── server.js
│   ├── systemDB
│   └── topics
│       ├── main.ss
│       └── systemDB
│           ├── 000003.log
│           ├── CURRENT
│           ├── LOCK
│           ├── LOG
│           └── MANIFEST-000002
├── clients
│   ├── slack.js
│   └── telnet.js
├── lib
│   ├── dict.js
│   ├── getreply.js
    etc

├── node_modules
│   ├── WNdb
│   │   ├── LICENSE
│   │   ├── README.md
...
│   ├── should

│   ├── string

├── package.json
├── plugins
├── readme.md
├── systemDB
└── test

```

where the package.json is
```json
{
  "name": "superscript",
  "version": "0.4.3",
...
```

**Comment by dcsan** [comment]
I *could* run it with the global install but eventually I'd like to integrate superscript with meteor so would prefer to know how to config in a more self-contained way... (this is probably just basic npm path stuff, i'll probably figure it out eventually %_%

**Comment by silentrob** [comment]
So the way I run it is create a folder for your bot (cbot) and then run  "npm init" (hit yes to everything)
Once that is done do "npm install superscript --save"

I have created a separate file for managing my topics called bootstrap.js 
https://gist.github.com/silentrob/61d3c0596afe89afb8b4

Hope that helps, and you are not being dense, if you have any questions or need any help just LMK.

**Comment by silentrob** [comment]
And to your point about 

    var net             = require("net");
    var superscript     = require("superscript");

That could mean global or within the project.

However if you cloned the repo and want to manage superscript that way then you will want to look and using npm link. In that cause I would recommend cloning the repo outside your bot folder and npm link will bring it in magically.

**Comment by dcsan** [comment]
thanks for your help. I went through those steps.
now stuck on:

TypeError: Object #<SuperScript> has no method 'userConnect'

pretty sure i:m running the latest version, I did remove the global install.
(however i noted the `init` script is left behind? are there versions of that too?)

also may want to let people know they need mongod running too.

```bash
which init
/usr/local/bin/init

head `which init`
#!/usr/bin/env node

/**
 * Module dependencies.
 */

var program = require('commander');
var fs = require("fs");
var path = require("path");

```

```
bot2> node server.js

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: failed to connect to [localhost:27017]
    at null.<anonymous> (/Users/dc/dev/shumi/bot2/bot2/node_modules/superscript/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:555:74)
    at EventEmitter.emit (events.js:106:17)
    at null.<anonymous> (/Users/dc/dev/shumi/bot2/bot2/node_modules/superscript/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:150:15)
    at EventEmitter.emit (events.js:98:17)
    at Socket.<anonymous> (/Users/dc/dev/shumi/bot2/bot2/node_modules/superscript/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:415:13)
bot2> l
total 24
0 drwxr-xr-x  10 dc  staff   340B Jan 24 16:06 ./
0 drwxr-xr-x   3 dc  staff   102B Jan 24 16:02 ../
8 -rw-r--r--   1 dc  staff   557B Jan 24 16:06 data.json
0 drwxr-xr-x   2 dc  staff    68B Jan 24 16:02 logs/
0 drwxr-xr-x   4 dc  staff   136B Jan 24 16:04 node_modules/
8 -rw-r--r--   1 dc  staff   271B Jan 24 16:04 package.json
0 drwxr-xr-x   2 dc  staff    68B Jan 24 16:02 plugins/
8 -rw-r--r--   1 dc  staff   2.1K Jan 24 16:02 server.js
0 drwxr-xr-x   8 dc  staff   272B Jan 24 16:06 systemDB/
0 drwxr-xr-x   3 dc  staff   102B Jan 24 16:02 topics/
bot2> head server.js 
// Run this and then telnet to localhost:2000 and chat with the bot

var net             = require("net");
var superscript     = require("superscript");

var options = {};
var sockets = [];

var botHandle = function(err, bot) {
    
bot2> cat topics/main.ss 
+ ~emohello [*~2]
- Hi!
- Hi, how are you?
- How are you?
- Hello
- Howdy
- Ola%                                                                                                                                         bot2> ls node_modules 
superscript/

```

OK so i need to run mongod separately, which i did.
and now we can startup OK:

```
bot2> node server.js 
TCP server running on port 2000.

User '127.0.0.1:49418' has connected.

/Users/dc/dev/shumi/bot2/bot2/server.js:56
    bot.userConnect(socket.name);
        ^
TypeError: Object #<SuperScript> has no method 'userConnect'
    at Server.newSocket (/Users/dc/dev/shumi/bot2/bot2/server.js:56:9)
    at Server.EventEmitter.emit (events.js:95:17)
    at TCP.onconnection (net.js:1191:8)

```

but as soon as i connect it will crash.

**Comment by silentrob** [comment]
Arg. Sorry I'm moving things a little to quickly. I just deprecated userConnect and added Mongo on thursday. Just comment it out and it should work.

**Comment by silentrob** [comment]
If you need any help Im also hanging out in superscript on freenode (IRC)

**Comment by dcsan** [comment]
awesome, it works :) thanks for your help!
now to try out some other commands!

**Comment by dcsan** [comment]
closing.
