### ISSUE TITLE
node-lemmer failing to install on ubuntu 14

### ISSUE THREAD

**Issue by ganarajpr** [silentrob/superscript#70]
Here is the log from trying to install superscript 
```
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Linux 3.16.0-31-generic
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ganaraj/.node/lib/node_modules/superscript/node_modules/node-lemmer
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 

> WNdb@3.1.1 postinstall /home/ganaraj/.node/lib/node_modules/superscript/node_modules/WNdb
> node unpack.js WNdb-3.1.tar.gz

Extracting WNdb-3.1.tar.gz

npm ERR! Linux 3.16.0-31-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "superscript"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! node-lemmer@0.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-lemmer@0.1.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the node-lemmer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-lemmer
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ganaraj/IdeaProjects/npm-debug.log
```

**Comment by silentrob** [comment]
node-lemmer does not seem to be compatible with node 0.12. I will see what needs to be fixed and perhaps send him a pull request.

**Comment by ganarajpr** [comment]
That project seems to have been abandoned ( perhaps ? )  - Last commit was feb 2014. 

I found an alternative 
https://github.com/Planeshifter/node-wordnet-magic which MIGHT have what you are looking for ( lemmatization! ).

But the problem is the same - even that one fails to install on ubuntu 14

**Comment by silentrob** [comment]
We will find a way to make it work... I might need to fork it or use the wornet lemma. I originally choose node-lemma because it was slightly faster - and one less thing I needed to write at the time.

**Comment by silentrob** [comment]
Okay, this dependancy has been removed, It should work better now try 0.7.0.
