### ISSUE TITLE
error on starting up bot

### ISSUE THREAD

**Issue by rayearl** [silentrob/superscript#71]
started with new amazon instance loading up bitnami stack of node, mongo, etc.

running through the tutorial from your article: https://medium.com/@rob_ellis/slack-superscript-rise-of-the-bots-bba8506a043c

whether i create the weather.js plugin or prior to that with just the "i'm not in the room" setup... i parse successfully but when i fire up the bot i keep getting this error:

bitnami:~/apps/slackbot$ sudo node server.js
Keys [ 'OxMpcCgN' ]

/opt/bitnami/apps/slackbot/node_modules/mongoose/lib/utils.js:413
        throw err;
              ^
TypeError: Cannot call method 'save' of undefined
    at Promise.<anonymous> (/opt/bitnami/apps/slackbot/node_modules/superscript/
lib/topics/import.js:143:13)
    at Promise.<anonymous> (/opt/bitnami/apps/slackbot/node_modules/mongoose/nod
e_modules/mpromise/lib/promise.js:172:8)
    at Promise.emit (events.js:95:17)
    at Promise.emit (/opt/bitnami/apps/slackbot/node_modules/mongoose/node_modul
es/mpromise/lib/promise.js:84:38)
    at Promise.reject (/opt/bitnami/apps/slackbot/node_modules/mongoose/node_mod
ules/mpromise/lib/promise.js:111:15)
    at Promise.error (/opt/bitnami/apps/slackbot/node_modules/mongoose/lib/promi
se.js:95:15)
    at Promise.<anonymous> (/opt/bitnami/apps/slackbot/node_modules/mongoose/lib
/model.js:1543:31)
    at Promise.<anonymous> (/opt/bitnami/apps/slackbot/node_modules/mongoose/nod
e_modules/mpromise/lib/promise.js:172:8)
    at Promise.emit (events.js:95:17)
    at Promise.emit (/opt/bitnami/apps/slackbot/node_modules/mongoose/node_modul
es/mpromise/lib/promise.js:84:38)

**Comment by silentrob** [comment]
Wow, setting it up on EC2. That is impressive. I just want to verify you are using node 0.10.x and have mongo installed / running.

**Comment by rayearl** [comment]
Amazon allows a free micro instance for a year so good platform to play on!
node = 0.10.35
mongo = 2.6.7

**Comment by rayearl** [comment]
debug parse output: 
parse topics
  Normalizer Loaded File +0ms { key: '_sys', file: 'systemessentials.txt' }
  Normalizer Loaded File +7ms { key: '_extra', file: 'substitutes.txt' }
  Normalizer Loaded File +171ms { key: '_contractions', file: 'contractions.txt'
 }
  Normalizer Loaded File +21ms { key: '_interjections', file: 'interjections.txt
' }
  Normalizer Loaded File +75ms { key: '_britsh', file: 'british.txt' }
  Normalizer Loaded File +156ms { key: '_spellfix', file: 'spellfix.txt' }
  Normalizer Loaded File +476ms { key: '_texting', file: 'texting.txt' }
  Normalizer Done Reading Subs +24ms
  Normalizer Done Loading files +1ms
  ParseContents Trigger Found +0ms :WH * weather *~2 in *
  RegexReply WIDTH STAR +0ms ~2  *~2
  ParseContents Response: +1s ^weather()
  Parse Sorting Topics +0ms
  Parse Sorting triggers... +0ms
  Parse Analyzing topic random +0ms
  Sort Sorting triggers with priority 0 +0ms
  Sort Has a * wildcard with 5 words. +0ms
  Sort ip=0 +1ms
  Parse Sorting Previous Topics +3ms
  Parse Sorting triggers... +0ms
  Sort Sorting reverse triggers for %Previous groups... +0ms
Time to Process 2.669 seconds
Number of topics 1 parsed.
Number of triggers 1 parsed.
Number of replies 1 parsed.
Saved output to data.json

**Comment by rayearl** [comment]
and starting up the server: 

bitnami:~/apps/slackbot$ sudo DEBUG=*,-Utils node server.js
  Normalizer Loaded File +0ms { key: '_sys', file: 'systemessentials.txt' }
  Normalizer Loaded File +16ms { key: '_extra', file: 'substitutes.txt' }
  Normalizer Loaded File +181ms { key: '_contractions', file: 'contractions.txt'
 }
  Normalizer Loaded File +19ms { key: '_interjections', file: 'interjections.txt
' }
  Normalizer Loaded File +75ms { key: '_britsh', file: 'british.txt' }
  Normalizer Loaded File +165ms { key: '_spellfix', file: 'spellfix.txt' }
  Normalizer Loaded File +436ms { key: '_texting', file: 'texting.txt' }
  Normalizer Done Reading Subs +7ms
  Normalizer Done Loading files +0ms
  Gambit Normaizer Loaded. +0ms
  Importer Find or create +0ms random
  mquery findOne +0ms { name: 'random' } { fields: undefined }
  mquery findOne +35ms { id: 'xTW7Iyjr' } { fields: undefined }
Keys [ 'w1z8JzjS' ]

/opt/bitnami/apps/slackbot/node_modules/mongoose/lib/utils.js:413
        throw err;
              ^
TypeError: Cannot call method 'save' of undefined
    at Promise.<anonymous> (/opt/bitnami/apps/slackbot/node_modules/superscript/
lib/topics/import.js:143:13)
    at Promise.<anonymous> (/opt/bitnami/apps/slackbot/node_modules/mongoose/nod
e_modules/mpromise/lib/promise.js:172:8)
    at Promise.emit (events.js:95:17)
    at Promise.emit (/opt/bitnami/apps/slackbot/node_modules/mongoose/node_modul
es/mpromise/lib/promise.js:84:38)
    at Promise.reject (/opt/bitnami/apps/slackbot/node_modules/mongoose/node_mod
ules/mpromise/lib/promise.js:111:15)
    at Promise.error (/opt/bitnami/apps/slackbot/node_modules/mongoose/lib/promi
se.js:95:15)
    at Promise.<anonymous> (/opt/bitnami/apps/slackbot/node_modules/mongoose/lib
/model.js:1543:31)
    at Promise.<anonymous> (/opt/bitnami/apps/slackbot/node_modules/mongoose/nod
e_modules/mpromise/lib/promise.js:172:8)
    at Promise.emit (events.js:95:17)
    at Promise.emit (/opt/bitnami/apps/slackbot/node_modules/mongoose/node_modul
es/mpromise/lib/promise.js:84:38)

**Comment by silentrob** [comment]
Please upgrade to node 0.12 and try again.
